language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
         apt:
            packages:
               - cmake
               - cmake-data
            sources:
               - sourceline: 'ppa:george-edison55/cmake-3.x'
      before_install:
        - curl -sS "https://www.codeon.de/dists/codeon-pub.asc" | sudo apt-key add -
        - echo "deb [arch=amd64] http://download.codeon.de `lsb_release -c -s` main" | sudo tee /etc/apt/sources.list.d/codeon.de-main.list
        - curl -sS "https://www.mulle-kybernetik.com/dists/debian-admin-pub.asc" | sudo apt-key add -
        - echo "deb [arch=all] http://www.mulle-kybernetik.com `lsb_release -c -s` main" | sudo tee "/etc/apt/sources.list.d/mulle-kybernetik.com-main.list" > /dev/null
        - sudo apt-get update
        - sudo apt-get install -y mulle-objc-developer

    - os: osx
      osx_image: "xcode9.4"
      before_install:
        - "brew update"
        - "brew install mulle-kybernetik/software/mulle-objc-developer"


script:
  - "ls /usr/local/share/mulle-sde/extensions/mulle-sde/cmake/project/executable/"
  - "MULLE_SDE_EXTENSION_BASE_PATH=\"${PWD}/src\" mulle-sde -vvv -lx -ld init -d exe -m mulle-foundation/objc-developer executable"
  - "cd exe"
#  - "MULLE_CRAFT_MAIN_PROJECT_MAKE_FLAGS=\"-vvv -ld\" mulle-sde -v craft"
  - "ls -l"
  - "ls /usr/local/share/mulle-sde/extensions/mulle-sde/cmake/project/executable/"
#  - "cd .."
#  - "MULLE_SDE_EXTENSION_BASE_PATH=\"${PWD}/src\" mulle-sde init -d lib -m mulle-foundation/objc-developer library"
#  - "cd lib"
#  - "mulle-sde -v craft"
#  - "cd .."

